[upstream]
default_base_url = "https://api.qnaigc.com"
# Use client API keys (x-goog-api-key, x-api-key) as 'Authorization: Baerer' token for openai-completions
budget_to_effort_low = 8000      # < 8000 tokens → "low"
budget_to_effort_medium = 20000  # < 20000 tokens → "medium"
budget_to_effort_high = 0        # >= 2000 or 0 = always "high" (or use a threshold)

[models.claude]
upstream_mode = "anthropic-messages"
#base_url = "https://api.qnaigc.com"
base_url = "http://localhost:4000"
api_key = "sk-17ac71ed56aee29*"
#"meituan/longcat-flash" = ["meituan/longcat-flash-lite", "", ""]
#base_url = "https://api.example-ai.com"
#"claude-4.5-sonnet" = ["claude-opus-4-20250514", "", ""]
#api_key = "sk-***"
#"claude-4.5-sonnet" = ["claude-opus-4-20250514", "", ""]
#"claude-4.6-sonnet" = ["claude-opus-4-1-20250805", "", ""]
"claude-opus-4-6" = ["claude-opus-4-6", "", ""]
"claude-sonnet-4-6" = ["claude-sonnet-4-6", "", ""]
"claude-sonnet-4-5" = ["claude-sonnet-4-5", "", ""]
"claude-haiku-4-5" = ["claude-haiku-4-5", "", ""]

[models.free]
base_url = "https://api.qnaigc.com"
upstream_mode = "openai-completions"
api_key = "sk-17ac71ed56aee29***"
"stepfun/step-flash-free" = ["stepfun/step-3.5-flash", "", ""]
"trinity-free" = ["arcee-ai/trinity-large-preview" , "", ""]

[models.gemini]
upstream_mode = "gemini-generatecontent"
base_url = "https://api.example.com"
api_key = "sk-***"
#"gemini-3.1-pro-preview" = ["", "", ""]
"gemini-3.0-flash-preview" = ["gemini-3-flash-preview", "", ""]
# "gemini-2.5-flash" = ["", "", ""]

[models.default]
"llama" = ["llama3.1-8B", "sdk://localhost", ""]
#"deepseek/deepseek-v3.2-251201" = ["", "", ""]
#upstream_mode = "openai-completions"
